#ifndef SPVM_SPVM_ARRAY_H
#define SPVM_SPVM_ARRAY_H

#include "spvm_base.h"

// SPVM_SPVM_ARRAY
struct SPVM_array {
  int8_t type;
  int8_t value_type;
  int32_t ref_count;
  int32_t length;
};

enum {
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_BYTE,
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_SHORT,
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_INT,
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_LONG,
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_FLOAT,
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_DOUBLE,
  SPVM_SPVM_ARRAY_C_VALUE_TYPE_OBJECT,
};

#endif
