=head1 NAME

SPVM::Document::Modules - SPVM Standard Modules(BETA before 1.0)

=head1 SPVM Standard Modules

=head2 SPVM::CORE

L<SPVM::CORE> - SPVM Standard Functions

=head2 SPVM::Byte

L<SPVM::Byte> - Byte Utility

=head2 SPVM::Short

L<SPVM::Short> - Short Utility

=head2 SPVM::Int

L<SPVM::Int> - Int Utility

=head2 SPVM::Long

L<SPVM::Long> - Long Utility

=head2 SPVM::Float

L<SPVM::Float> - Float Utility

=head2 SPVM::Double

L<SPVM::Double> - Double Utility

=head2 SPVM::Math

L<SPVM::Math> - Math Library

=head2 SPVM::Arrays

L<SPVM::Arrays> - Arrays Utility
