=head1 NAME

SPVM::Document::StandardFunction - SPVM Standard Function(BETA before 1.0)

=head1 SPVM Standard Function

=head1 FUNCTIONS

=head2 print

Print string to stdout.

  sub print ($value : byte) : native void;

=head2 warn

Print string to stderr.

  sub warn ($value : byte[]) : native void;

=head2 time

Get epoch time.

  sub time () : native long;
