=head1 NAME

SPVM::Document::StandardFunction - SPVM Standard Function(BETA before 1.0)

=head1 SPVM Standard Function

=head1 FUNCTIONS

=head2 print

Print string to stdout.

  sub print ($value : byte) : native void;

=head2 print_byte

Print byte value to stdout.

  sub print_byte ($value : byte) : native void;

=head2 print_short

Print short value to stdout.

  sub print_short ($value : short) : native void;

=head2 print_int

Print int value to stdout.

  sub print_int ($value : int) : native void;

=head2 print_long

Print long value to stdout.

  sub print_long ($value : long) : native void;

=head2 print_float

Print float value to stdout.

  sub print_float ($value : float) : native void;

=head2 print_double

Print double value to stdout.

  sub print_double ($value : double) : native void;

=head2 print_err

Print string to stderr.

  sub print_err ($value : byte[]) : native void;

=head2 print_err_byte

Print byte value to stderr.

  sub print_err_byte ($value : byte) : native void;

=head2 print_err_short

Print short value to stderr.

  sub print_err_short ($value : short) : native void;

=head2 print_err_int

Print int value to stderr.

  sub print_err_int ($value : int) : native void;

=head2 print_err_long

Print long value to stderr.

  sub print_err_long ($value : long) : native void;

=head2 print_err_float

Print float value to stderr.

  sub print_err_float ($value : float) : native void;

=head2 print_err_double

Print double value to stderr.

  sub print_err_double ($value : double) : native void;

=head2 time

Get epoch time.

  sub time () : native long;
