#!/usr/bin/env perl

use strict;
use warnings;
use File::Path qw(make_path);

my ($class_name, $dir) = @ARGV;

unless (length $class_name && length $dir) {
  die "Usage: $0 <class_name> <dir>\n";
}

my @class_parts = split('::', $class_name);
my $file_name = pop @class_parts;
my $class_name_dir = "$dir/" . join('/', @class_parts);
make_path($class_name_dir);

my $spvm_file = "$class_name_dir/$file_name.spvm";
my $c_file    = "$class_name_dir/$file_name.c";
my $pm_file   = "$class_name_dir/$file_name.pm";

open my $fh_spvm, '>', $spvm_file
  or die "Can't open file '$spvm_file':$!";
open my $fh_c,    '>', $c_file    or die $!
  or die "Can't open file '$c_file':$!";
open my $fh_pm,   '>', $pm_file   or die $!
  or die "Can't open file '$pm_file':$!";

my $class_name_c = $class_name;
$class_name_c =~ s/::/__/g;
print $fh_c qq|#include "spvm_native.h"\n\n|;

print $fh_spvm "class $class_name {\n";

print $fh_pm <<"EOS";
=head1 Name

$class_name

=head1 Class Methods

EOS

while (my $line = <>) {
  chomp $line;
  next unless $line =~ /\S/;
  
  my ($constant_name, $type) = split(/\s*:\s*/, $line);
  $type ||= 'int';
  
  my $return_type;
  my $set_value;
  
  if ($type eq 'byte') {
    $return_type = 'byte';
    $set_value = 'stack[0].bval = (int8_t)$constant_name;';
  }
  elsif ($type eq 'short') {
    $return_type = 'short';
    $set_value = 'stack[0].sval = (int16_t)$constant_name;';
  }
  elsif ($type eq 'int') {
    $return_type = 'int';
    $set_value = 'stack[0].ival = (int32_t)$constant_name;';
  }
  elsif ($type eq 'long') {
    $return_type = 'long';
    $set_value = 'stack[0].lval = (int64_t)$constant_nameT;';
  }
  elsif ($type eq 'float') {
    $return_type = 'float';
    $set_value = 'stack[0].fval = (float)$constant_name;';
  }
  elsif ($type eq 'double') {
    $return_type = 'double';
    $set_value = 'stack[0].dval = (double)$constant_name;';
  }
  elsif ($type eq 'string') {
    $return_type = 'string';
    $set_value = 'stack[0].oval = env->new_string_nolen(env, stack, $constant_name);';
  }
  else {
    warn "Unknown type: $type for $constant_name. Ignoring.\n";
    next;
  }
  
  # SPVM
  print $fh_spvm "  native static method $constant_name : $return_type ();\n";
  
  # C
  print $fh_c <<"EOS";
int32_t SPVM__${class_name_c}__$constant_name(SPVM_ENV* env, SPVM_VALUE* stack) {
#ifdef $constant_name
  $set_value
  return 0;
#else
  env->die(env, stack, "$constant_name is not defined on the system", __func__, FILE_NAME, __LINE__);
  return SPVM_NATIVE_C_BASIC_TYPE_ID_ERROR_NOT_SUPPORTED_CLASS;
#endif
}

EOS

  # PM
  print $fh_pm <<"EOS";
=head2 $constant_name

C<static method $constant_name : $return_type ();>

Returns the value of C<$constant_name>. If this constant is not defined on the system, L<Error::NotSupported|SPVM::Error::NotSupported> exception is thrown.

EOS
}

print $fh_spvm "}\n";

__END__

use strict;
use warnings;

my $class_name = shift;
my $type = shift;

while (my $line = <>) {
  chomp $line;
  
  my $constant_name = $line;
  
  if ($type eq 'spvm') {
    my $output = "  native static method $constant_name : int ();\n\n";
    
    print $output;
  }
  elsif ($type eq 'c') {
    my $class_name_c = $class_name;
    $class_name_c =~ s/::/__/g;
    
    my $output = <<"EOS";
int32_t SPVM__${class_name_c}__$constant_name(SPVM_ENV* env, SPVM_VALUE* stack) {

#ifdef $constant_name
  stack[0].ival = $constant_name;
  return 0;
#else
  env->die(env, stack, "$constant_name is not defined on the system", __func__, FILE_NAME, __LINE__);
  return SPVM_NATIVE_C_BASIC_TYPE_ID_ERROR_NOT_SUPPORTED_CLASS;
#endif
  
}

EOS

    print $output;
  }
  elsif ($type eq 'pm') {
    my $output = <<"EOS";
=head2 $constant_name

C<static method $constant_name : int ();>

Returns the value of C<$constant_name>. If this constant is not defined on the system, L<Error::NotSupported|SPVM::Error::NotSupported> exception is thrown.

EOS
    
    print $output;
  }
  else {
    die;
  }
}
