#!perl

use strict;
use warnings;

use SPVM();
use SPVM::Builder::Info;
use SPVM::Builder::Util;

my @argv;

SPVM::Builder::Util::getopt
  # spvminfo and spvm shared
  'h|help'          => \my $help,
  'v|version'       => \my $show_version,
  'I|include-dir=s' => \my @include_dirs,
  
  # spvminfo only
  'r|required-resources' => \my $print_required_resources,
;

if ($help) {
  print SPVM::Builder::Util::extract_usage;
  exit 0;
}
elsif ($show_version) {
  my $version_string = "spvminfo v$SPVM::VERSION";
  print "$version_string\n";
  exit 0;
}

my $class_name = shift;

unless (defined $class_name) {
  warn "<class name> is required.\n\n";
  warn SPVM::Builder::Util::extract_usage;
  exit 255;
}

my @original_include_dirs = @include_dirs;
push @include_dirs, map { "$_/SPVM" } @INC;
unshift @INC, map { $_ =~ s/[\\\/]SPVM$//; $_; } @original_include_dirs;

my $build_info = SPVM::Builder::Info->new(
  class_name => $class_name,
  build_dir => $build_dir,
  include_dirs => \@include_dirs,
);

if ($print_required_resources) {
  my $lines = $build_info->get_required_resource_json_lines;
  print "$_\n" for @$lines;
  exit 0;
}

$build_info->build_info_file;

=encoding utf8

=head1 Name

spvminfo - SPVM class information

=head1 Description

The spvminfo command gets class information

=head1 Usage

  usage: spvminfo [<options>] <class name>
    
    spvminfo -I lib/SPVM Myapp
  
  options:
    -h, --help                     Shows this message
    -v, --version                  Shows the version
    -I, --include-dir <directory>  Adds a include directory
    -r, --required-resources       Prints required resources in JSON lines

=head1 Copyright & License

Copyright 2023 Yuki Kimoto. All Rights Reserved.

MIT License.
